# -*- coding: utf-8 -*-
"""Rosalind_Projeto9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xbf7FwbDuXLsnuy-zZ4PMAaEbZTYQRQO
"""

with open("/content/drive/MyDrive/Rosalind/Projeto9/rosalind_subs.txt") as f:
        contents = f.read()

lista=contents.split("\n")

string=lista[0]
string

t=lista[1]
t

tam=len(t)
tam

pos=[]
# Para conjunto contendo a palavra "ATAT"
for i in range (len(string)):
  # dividi a string em grupos do tamanho da string que quer achar
    item=string[i:tam+i]
    #print(item)
    #print(i)
    if item==t:
      pos+=[i+1]
pos
print(*pos)